# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
target 'Demo' do
    use_frameworks!

    pod 'T', :path=>'../'
    
    target 'DemoTests' do
        inherit! :search_paths
    end
end

target 'CoreDataOnly' do
  use_frameworks!

  pod 'T/CoreData', :path=>'../'
end

target 'CoreGraphicsOnly' do
  use_frameworks!

  pod 'T/CoreGraphics', :path=>'../'
end

target 'FoundationOnly' do
  use_frameworks!

  pod 'T/Foundation', :path=>'../'
end

target 'UIOnly' do
  use_frameworks!

  pod 'T/UI', :path=>'../'
end
